<a href="https://colab.research.google.com/github/danamolodi/Python-Pandas-Training/blob/main/Python_Panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# تعریف متغیرهای پایه برای سنسور
sensor_id = 1
sensor_name = "Temperature Sensor"
current_value = 520.5
is_active = True

# چاپ مقادیر در خروجی
print("شناسه سنسور:", sensor_id)
print("نوع سنسور:", sensor_name)
print("مقدار فعلی:", current_value)

main data :
     cycle  sensor_temp
0      1        518.6
1      2        520.1
2      3        517.9
3      4        521.5
4      5        519.0
5      6        522.3
6      7        520.8
   cycle  sensor_temp  temp_moving_avg
0      1        518.6              NaN
1      2        520.1              NaN
2      3        517.9       518.866667
3      4        521.5       519.833333
4      5        519.0       519.466667
5      6        522.3       520.933333
6      7        520.8       520.700000

In [ ]:
# Day 2: Working with Python Lists for sensor historical data

# 1. Creating a list of recorded temperatures
temperature_readings = [520.5, 521.2, 519.8, 522.1, 520.0]

# 2. Extracting specific elements (Index always starts at 0)
first_reading = temperature_readings[0]
last_reading = temperature_readings[-1]

print("All Readings:", temperature_readings)
print("First Reading:", first_reading)
print("Last Reading:", last_reading)
print("the length of the list 'temperature_readings' :  ",len(temperature_readings))

# 3. Adding a new temperature reading to the end of the list
temperature_readings.append(523.4)
deleted_item=temperature_readings.pop(-1)
print("the deleted item :",deleted_item)
print("now we delete the last item to see the cahnges : ",temperature_readings.pop(-1))

All Readings: [520.5, 521.2, 519.8, 522.1, 520.0]
First Reading: 520.5
Last Reading: 520.0
the length of the list 'temperature_readings' :   5
the deleted item : 523.4
now we delete the last item to see the cahnges :  520.0

In [ ]:
# Day 3: Working with Python Dictionaries for sensor metadata

# 1. Creating a dictionary for a specific sensor
sensor_data = {
    "id": 101,
    "name": "Temperature Sensor",
    "unit": "Celsius",
    "is_active": True,
    "current_value": 523.4
}

# 2. Accessing a specific value using its key
sensor_name = sensor_data["name"]
current_temp = sensor_data["current_value"]

print("Sensor Data Dictionary:", sensor_data)
print("Target Sensor Name:", sensor_name)
print("Current Temperature:", current_temp)

# 3. Adding a new key-value pair to the dictionary
sensor_data["location"] = "Engine Core"
print("Updated Sensor Data:", sensor_data)


# 4. Updating an existing value
sensor_data["current_value"] = 525.1
print("Sensor Data after temperature update:", sensor_data)

#5. doing the mini-task
print("keys : ",sensor_data.keys())
del sensor_data["is_active"]
print(sensor_data)

Sensor Data Dictionary: {'id': 101, 'name': 'Temperature Sensor', 'unit': 'Celsius', 'is_active': True, 'current_value': 523.4}
Target Sensor Name: Temperature Sensor
Current Temperature: 523.4
Updated Sensor Data: {'id': 101, 'name': 'Temperature Sensor', 'unit': 'Celsius', 'is_active': True, 'current_value': 523.4, 'location': 'Engine Core'}
Sensor Data after temperature update: {'id': 101, 'name': 'Temperature Sensor', 'unit': 'Celsius', 'is_active': True, 'current_value': 525.1, 'location': 'Engine Core'}
keys :  dict_keys(['id', 'name', 'unit', 'is_active', 'current_value', 'location'])
{'id': 101, 'name': 'Temperature Sensor', 'unit': 'Celsius', 'current_value': 525.1, 'location': 'Engine Core'}

In [ ]:
# Day 4: Working with Conditional Statements (If/Else) for sensor thresholds

# 1. Defining a sensor's current temperature and the safety threshold
current_temperature = 526.4
safety_threshold = 525.0

# 2. Checking the condition
if current_temperature > safety_threshold:
    print("Warning: Sensor temperature has exceeded the safety threshold!")
    print("Current Temp:", current_temperature)
else:
    print("Status: Normal. Sensor is operating within safe limits.")

# 3. Using elif (else if) for multiple conditions
vibration_level = 0.8

if vibration_level < 0.5:
    print("Vibration Status: Low")
elif vibration_level <= 1.0:
    print("Vibration Status: Moderate (Monitor closely)")
else:
    print("Vibration Status: Critical! Immediate inspection required.")

Warning: Sensor temperature has exceeded the safety threshold!
Current Temp: 526.4
Vibration Status: Moderate (Monitor closely)

In [ ]:
# Day 5: Using For Loops to iterate through sensor data

# 1. Defining a list of temperature readings
vibration_levels=[0.1,0.12,0.35,0.81,0.711]
temperature_readings = [520.5, 521.2, 519.8, 526.1, 520.0]
safety_threshold = 525.0

# 2. Iterating through the list using a for loop
for temp in temperature_readings:
    # 3. Checking condition for each individual reading
    if temp > safety_threshold:
        print("Warning: High temperature detected -", temp)
    else:
        print("Normal temperature -", temp)
for vib in vibration_levels:
    if vib > 0.7 :
      print("Critical vibration detected: ",vib)
    else:
      print("Vibration normal: ",vib)

Normal temperature - 520.5
Normal temperature - 521.2
Normal temperature - 519.8
Warning: High temperature detected - 526.1
Normal temperature - 520.0
Vibration normal:  0.1
Vibration normal:  0.12
Vibration normal:  0.35
Critical vibration detected:  0.81
Critical vibration detected:  0.711

In [ ]:
# Day 6: Defining Functions (def) for reusable calculations

# 1. Defining a function to calculate total operating cycles
def calculate_total_cycles(previous_cycles, new_cycles):
    total = previous_cycles + new_cycles
    return total

# 2. Calling the function with specific numbers for different engines
engine_1_total = calculate_total_cycles(150, 45)
engine_2_total = calculate_total_cycles(210, 30)

# 3. Printing the results
print("Engine 1 Total Cycles:", engine_1_total)
print("Engine 2 Total Cycles:", engine_2_total)

Engine 1 Total Cycles: 195
Engine 2 Total Cycles: 240

In [ ]:
# Day 7: Integration of Functions, Loops, and Conditionals

# 1. Defining a function to filter critical temperatures
def filter_critical_temperatures(temperatures_list, threshold):
    critical_values = [] # Creating an empty list to store dangerous values

    # 2. Looping through the provided list
    for temp in temperatures_list:
        # 3. Checking the condition
        if temp > threshold:
            critical_values.append(temp) # Adding to the list if the condition is met

    return critical_values # Returning the final filtered list

# 4. Creating a list of sensor readings and defining the limit
sensor_readings = [520.1, 526.4, 522.3, 528.0, 519.9, 530.1]
safety_limit = 525.0

# 5. Calling the function and printing the result
dangerous_temps = filter_critical_temperatures(sensor_readings, safety_limit)
print("All Sensor Readings:", sensor_readings)
print("Critical Temperatures Detected:", dangerous_temps)

All Sensor Readings: [520.1, 526.4, 522.3, 528.0, 519.9, 530.1]
Critical Temperatures Detected: [526.4, 528.0, 530.1]

In [ ]:
# Day 8: Introduction to Pandas and loading tabular data

# 1. Importing the pandas library (standard practice is to alias it as 'pd')
import pandas as pd

# 2. Creating a sample dataset simulating the engine sensor data
# Note: In a real scenario, you would use -> pd.read_csv("dataset.csv")
sensor_data_dict = {
    "engine_id": [1, 1, 1, 2, 2],
    "operational_cycle": [1, 2, 3, 1, 2],
    "sensor_1_temp": [518.67, 518.67, 518.67, 518.62, 518.61],
    "sensor_2_pressure": [641.82, 642.15, 642.35, 642.50, 642.10]
}

# 3. Converting the dictionary into a Pandas DataFrame (a structured table)
engine_dataframe = pd.DataFrame(sensor_data_dict)

# 4. Displaying the dataset
print("Initial Engine Data Preview:")
print(engine_dataframe)

Initial Engine Data Preview:
   engine_id  operational_cycle  sensor_1_temp  sensor_2_pressure
0          1                  1         518.67             641.82
1          1                  2         518.67             642.15
2          1                  3         518.67             642.35
3          2                  1         518.62             642.50
4          2                  2         518.61             642.10

In [ ]:
sensor_data_list={
    "engine_id" : [1,1,1,2,2],
    "operational_cycle" : [1,2,3,1,2],
    "sensor_1_temp": [518.67, 518.67, 518.67, 518.62, 518.61],
    "sensor_2_pressure": [641.82, 642.15, 642.35, 642.50, 642.10]
}

engine_data_form = pd.DataFrame(sensor_data_list)

print("initial engine data preview :")
print(engine_data_form,"\n")
#first task
two_first_rows = engine_data_form.head(2)
print("first two rows :\n")
print(two_first_rows)
#second task
engine_data_form.describe()

initial engine data preview :
   engine_id  operational_cycle  sensor_1_temp  sensor_2_pressure
0          1                  1         518.67             641.82
1          1                  2         518.67             642.15
2          1                  3         518.67             642.35
3          2                  1         518.62             642.50
4          2                  2         518.61             642.10

first two rows :

   engine_id  operational_cycle  sensor_1_temp  sensor_2_pressure
0          1                  1         518.67             641.82
1          1                  2         518.67             642.15

       engine_id  operational_cycle  sensor_1_temp  sensor_2_pressure
count   5.000000            5.00000       5.000000           5.000000
mean    1.400000            1.80000     518.648000         642.184000
std     0.547723            0.83666       0.030332           0.258902
min     1.000000            1.00000     518.610000         641.820000
25%     1.000000            1.00000     518.620000         642.100000
50%     1.000000            2.00000     518.670000         642.150000
75%     2.000000            2.00000     518.670000         642.350000
max     2.000000            3.00000     518.670000         642.500000

In [ ]:
import pandas as pd

# Day 9: Quick DataFrame Filtering (Micro-task to keep the streak)

# 1. Creating a simplified dataset
data = {
    "engine_id": [1, 1, 2, 2, 3],
    "sensor_temp": [518.67, 519.10, 518.62, 519.85, 518.55]
}
df = pd.DataFrame(data)

# 2. Filtering rows where sensor temperature is strictly greater than 519.00
critical_engines = df[df["sensor_temp"] > 519.00]

print("Filtered Data (Critical Temperatures):\n")
print(critical_engines)

Filtered Data (Critical Temperatures):

   engine_id  sensor_temp
1          1       519.10
3          2       519.85

In [ ]:
import pandas as pd

# 1. Loading the baseline dataset
sensor_records = {
    "engine_id": [1, 1, 2, 2],
    "sensor_temp": [518.67, 519.10, 518.62, 519.85]
}
airplane_data = pd.DataFrame(sensor_records)

# 2. Defining a nominal temperature for safe operation
nominal_temp = 518.60

# 3. Creating new columns
airplane_data["temperature_deviation"] = airplane_data["sensor_temp"] - nominal_temp

# 4. Creating the boolean column based on the condition
airplane_data["is_critical"] = airplane_data["sensor_temp"] > 519.00

# 5. Displaying the updated DataFrame
print("Updated Dataset with New Features:\n")
print(airplane_data)
(airplane_data.describe())

Updated Dataset with New Features:

   engine_id  sensor_temp  temperature_deviation  is_critical
0          1       518.67                   0.07        False
1          1       519.10                   0.50         True
2          2       518.62                   0.02        False
3          2       519.85                   1.25         True

       engine_id  sensor_temp  temperature_deviation
count    4.00000     4.000000               4.000000
mean     1.50000   519.060000               0.460000
std      0.57735     0.569034               0.569034
min      1.00000   518.620000               0.020000
25%      1.00000   518.657500               0.057500
50%      1.50000   518.885000               0.285000
75%      2.00000   519.287500               0.687500
max      2.00000   519.850000               1.250000

**Day 11: Handling Missing Data**

In [ ]:
import pandas as pd
import numpy as np

# Day 11: Handling Missing Data

# 1. Dataset with missing values (np.nan simulates missing sensor records)
sensor_data = {
    "engine_id": [1, 1, 2, 2, 3],
    "sensor_temp": [518.67, np.nan, 518.62, 519.85, np.nan]
}
df = pd.DataFrame(sensor_data)
print("Original Data:\n", df, "\n")

# 2. Strategy A: Drop any row containing missing data
df_dropped = df.dropna()
print("Data after dropping NaNs:\n", df_dropped, "\n")

# 3. Strategy B: Fill missing data with a nominal fixed value
df_filled = df.fillna(518.60)
print("Data after filling NaNs:\n", df_filled)

Original Data:
    engine_id  sensor_temp
0          1       518.67
1          1          NaN
2          2       518.62
3          2       519.85
4          3          NaN

Data after dropping NaNs:
    engine_id  sensor_temp
0          1       518.67
2          2       518.62
3          2       519.85

Data after filling NaNs:
    engine_id  sensor_temp
0          1       518.67
1          1       518.60
2          2       518.62
3          2       519.85
4          3       518.60

In [ ]:
import pandas as pd
import numpy as np

# Day 11: Handling Missing Data

# 1. Dataset with missing values (np.nan simulates missing sensor records)
sensor_data = {
    "engine_id": [1, 1, 2, 2, 3],
    "sensor_temp": [518.67, np.nan, 518.62, 519.85, np.nan]
}
df = pd.DataFrame(sensor_data)
print("Original Data:\n", df, "\n")

# 2. Strategy A: Drop any row containing missing data
df_dropped = df.dropna()
print("Data after dropping NaNs:\n", df_dropped, "\n")

# 3. Strategy B: Fill missing data with a nominal fixed value
df_filled = df.fillna(518.60)
print("Data after filling NaNs:\n", df_filled)

# 4. filling the missing data with the mean of sensor_temp

nominal_temp = df["sensor_temp"].mean()
df_filled_mean = df.fillna(nominal_temp)
print("Data after filling NaNs with mean:\n", df_filled_mean)

Original Data:
    engine_id  sensor_temp
0          1       518.67
1          1          NaN
2          2       518.62
3          2       519.85
4          3          NaN

Data after dropping NaNs:
    engine_id  sensor_temp
0          1       518.67
2          2       518.62
3          2       519.85

Data after filling NaNs:
    engine_id  sensor_temp
0          1       518.67
1          1       518.60
2          2       518.62
3          2       519.85
4          3       518.60
Data after filling NaNs with mean:
    engine_id  sensor_temp
0          1   518.670000
1          1   519.046667
2          2   518.620000
3          2   519.850000
4          3   519.046667

***Day 12: Grouping Data and Aggregation***

In [ ]:
import pandas as pd

# Day 12: Grouping Data (groupby)

# 1. Sample dataset representing multiple engines and their operational cycles
data = {
    "engine_id": [1, 1, 1, 2, 2, 3, 3, 3, 3],
    "cycle": [1, 2, 3, 1, 2, 1, 2, 3, 4],
    "sensor_temp": [518.67, 518.68, 518.69, 519.85, 519.82, 520.10, 520.15, 520.12, 520.18]
}
df = pd.DataFrame(data)
print("Original DataFrame:\n", df, "\n")

# 2. Grouping by engine_id to find the maximum cycle for each engine (End of Life)
# This logic is the core of our RUL calculation phase.
max_cycles = df.groupby("engine_id")["cycle"].max()
print("Maximum cycles per engine (Point of failure):\n", max_cycles)
#3. Task
mean_temp_per_engine = df.groupby("engine_id")["sensor_temp"].mean()
print("\n",mean_temp_per_engine)

Original DataFrame:
    engine_id  cycle  sensor_temp
0          1      1       518.67
1          1      2       518.68
2          1      3       518.69
3          2      1       519.85
4          2      2       519.82
5          3      1       520.10
6          3      2       520.15
7          3      3       520.12
8          3      4       520.18

Maximum cycles per engine (Point of failure):
 engine_id
1    3
2    2
3    4
Name: cycle, dtype: int64

 engine_id
1    518.6800
2    519.8350
3    520.1375
Name: sensor_temp, dtype: float64

**Day 13 : Merging Data**

In [ ]:
import pandas as pd

# Day 13: Merging DataFrames (pd.merge)

# 1. Main dataset (Sensor readings per cycle)
sensor_data = pd.DataFrame({
    "engine_id": [1, 1, 1, 2, 2],
    "cycle": [1, 2, 3, 1, 2],
    "sensor_temp": [518.67, 518.68, 518.69, 519.85, 519.82]
})
print("Main Data:\n", sensor_data, "\n")

# 2. Max cycles calculated in Day 12 (Point of failure)
max_cycles = pd.DataFrame({
    "engine_id": [1, 2],
    "max_cycle": [3, 2]
})
print("Max Cycles Data:\n", max_cycles, "\n")

# 3. Merging the two tables based on 'engine_id'
merged_df = pd.merge(sensor_data, max_cycles, on="engine_id", how="left")

merged_df["RUL"] = merged_df["max_cycle"] - merged_df["cycle"]
print("Merged DataFrame:\n", merged_df)

Main Data:
    engine_id  cycle  sensor_temp
0          1      1       518.67
1          1      2       518.68
2          1      3       518.69
3          2      1       519.85
4          2      2       519.82

Max Cycles Data:
    engine_id  max_cycle
0          1          3
1          2          2

Merged DataFrame:
    engine_id  cycle  sensor_temp  max_cycle  RUL
0          1      1       518.67          3    2
1          1      2       518.68          3    1
2          1      3       518.69          3    0
3          2      1       519.85          2    1
4          2      2       519.82          2    0

**Day 14: Rolling Window Operation**

In [ ]:
import pandas as pd

# Day 14: Rolling Window Operations (Moving Average)

# 1. Dataset representing sensor readings of a single engine over time
sensor_data = pd.DataFrame({
    "cycle": [1, 2, 3, 4, 5, 6, 7],
    "sensor_temp": [518.6, 520.1, 517.9, 521.5, 519.0, 522.3, 520.8]
})
print("Original Data:\n", sensor_data, "\n")

# 2. Calculating Rolling Mean (Window size = 3)
sensor_data["temp_moving_avg"] = sensor_data["sensor_temp"].rolling(window=3).mean()

# 3. Handling NaN values using backward fill (bfill)
sensor_data["temp_moving_avg"] = sensor_data["temp_moving_avg"].bfill()

print("Data with Rolling Mean and bfill:\n", sensor_data)

**Day 15: Data Normalization**

In [2]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Day 15: Data Normalization

# 1. Dataset with sensors in completely different scales
data = {
    "cycle": [1, 2, 3, 4, 5],
    "sensor_temp": [518.6, 520.1, 517.9, 521.5, 522.3],
    "sensor_pressure": [14.6, 14.1, 14.8, 13.9, 14.5]
}
df = pd.DataFrame(data)
print("Original Data:\n", df, "\n")

# 2. Initializing the Scaler
scaler = MinMaxScaler()

# 3. Scaling a single column (sensor_temp)
df[["sensor_temp_scaled","sensor_pressure_scaled"]] = scaler.fit_transform(df[["sensor_temp","sensor_pressure"]])
print("Data with Scaled Temperature:\n", df)

Original Data:
    cycle  sensor_temp  sensor_pressure
0      1        518.6             14.6
1      2        520.1             14.1
2      3        517.9             14.8
3      4        521.5             13.9
4      5        522.3             14.5

Data with Scaled Temperature:
    cycle  sensor_temp  sensor_pressure  sensor_temp_scaled  \
0      1        518.6             14.6            0.159091
1      2        520.1             14.1            0.500000
2      3        517.9             14.8            0.000000
3      4        521.5             13.9            0.818182
4      5        522.3             14.5            1.000000

   sensor_pressure_scaled
0                0.777778
1                0.222222
2                1.000000
3                0.000000
4                0.666667